image: Ubuntu1804  # образ для сборки

stack: node 10  # окружение

branches:
  only:
    - master  # ветка git

cache: node_modules  # кеширование

install:
  - yarn # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - yarn build   # команда сборки

test_script:
  - yarn lint && yarn test  # скрипт тестирования

environment:
  my_variable:
    secure: AHqZsGNbKL+RxqV2hVEAbGM8RTIGSbxiD1MI16xTYS+IXcuQqLd/6z/LalapwHdt
    var: abc

variables:
  NODE_IMAGE: node:10

deploy_script: # скрипт развёртывания
  - echo $NODE_IMAGE
  - echo $secure # это все попытки получить значения переменной secure
  - echo $env:secure
  - echo $env:my_variable
  - echo $env:my_variable:secure
  - echo $env:my_variable.secure
  - echo $env.secure
  - echo $env.my_variable.secure
  - echo $environment.my_variable.secure
  - echo $env:var
  - echo "text/$env:var:text"
  - git config --global credential.helper store
  - git config --global user.name AppVeyor
  - git config --global user.email ci@appveyor.com
  - echo "https://$secure:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - npx push-dir --dir=dist --branch=gh-pages --force --verbose
